version: "3.7"
services:
    vision:
        build:
            context: ./
            dockerfile: Dockerfile
        image: vision
        container_name: vision-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - vision

    db:
        image: mysql:8
        command: --max_allowed_packet=32505856
        container_name: vision-db
        restart: unless-stopped
        ports:
            - "3700:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-volumes/mysql:/var/lib/mysql
        networks:
            - vision

    nginx:
        image: nginx:alpine
        container_name: vision-nginx
        restart: unless-stopped
        ports:
            - "8060:80"
        volumes:
            - ./:/var/www
            - ./docker-volumes/nginx:/etc/nginx/conf.d/
        networks:
            - vision

    redis:
        container_name: vision-redis
        image: redis
        ports:
            - "6380:6379"
        volumes:
            - ./docker-volumes/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always
        networks:
            - vision

networks:
    vision:
        driver: bridge
